<!doctype html>
<html lang="es-PE">
<?php $this->load->view("head"); ?>
<body>
    <div id="section-header" data-section-id="header">
        <?php $this->load->view("header"); ?>
    </div>
    <main>
        <div data-content-for-index data-dynamic-sections="index">
            <!--Fin Pasos de registro-->
            <!--Sé parte de los profesores-->
            <div class="section background-dark color-teacher" data-reveal-units="seconds">
                <div class="sizer">
                    <div class="container">
                    <div class="panel">
                        <div class="panel__body fluid-video">
                                <h1>Términos y Condiciones</h1>
                                        <p>Los Términos y Condiciones que se expresan en este contrato constituyen las condiciones de uso y privacidad del servicio de la plataforma Cultura Imparable y demás servicios agregados que se prestan a los usuarios en la actualidad y a futuro por la empresa Cultura Emprendedora en su sitio web www.culturaemprendedora.online, tanto en su aplicación web a través del dominio culturaemprendedora.online como en su versión móvil para Android y IOS.</p>
                                    <h3>Consideraciones Preliminares</h3>
                                        <p> El usuario comprende y acepta libre, pleno y sin reservas todos y cada uno de los términos y condiciones que le asisten en este contrato, por simple causal de uso del servicio Cultura Emprendedora y demás servicios agregados, de los cuales será responsable sobre su cumplimiento. Si el usuario no está de acuerdo en su totalidad sobre lo dispuesto, no podrá hacer uso de los servicios prestados por Cultura Emprendedora.</p>
                                        <p>o Si el usuario es representante de alguna organización empresarial, da por entendido que está facultado para actuar en nombre de ella y, en consecuencia, obligarla frente a Cultura Emprendedora a aceptar todas las obligaciones derivadas de este contrato.</p>
                                        <p>o El usuario que acepte el presente contrato, debe ser legalmente apto para celebrarlo según lo permita su autonomía de la voluntad y las leyes que le sean aplicables en su país y, por tanto, da por entendido a Cultura Emprendedora que conoce previamente si está o no en capacidad de celebrar contratos a nombre propio o en representación de alguna organización.</p>
                                        <p>o Los términos y condiciones podrán ser modificados total o parcialmente, sin previo aviso o autorización por parte del usuario. Los cambios e implementaciones tendrán vigencia a partir del momento mismo en que sean publicados o insertados en el sitio web de Cultura Emprendedora o desde que sean notificados al usuario por cualquier medio; en todo caso, sea cual fuere el medio de divulgación, operarán con el primer aviso que obtenga.</p>
                                    <h3>Términos Usados</h3>
                                        <p>Las definiciones a continuación tendrán el siguiente significado en este contrato:</p>
                                        <p>o El término "contrato" o "acuerdo" hace referencia a este contrato y a sus Términos y Condiciones.</p>
                                        <p>o El término "leyes aplicables" hace referencia a las leyes que se aplican en España para este tipo de contratos.</p>
                                        <p>o El término "sitio" o "sitio web" hace referencia al sitio donde se prestan todos los servicios que Cultura Emprendedora ofrece, sin tener en cuenta posibles terceros relacionados con Cultura Emprendedora.</p>
                                        <p>o El término "servicio" o “servicios” hace referencia a la aplicación que ofrece Cultura Emprendedora en su sitio web y que opera desde el dominio culturaemprendedora.online También hace referencia al uso de la página web de Cultura Emprendedora y su centro de soporte.</p>
                                        <p>o Los términos "Sistema", "Sistema de información", “Aplicativo”, “Software”, “Plataforma”, “Plataforma Cultura Emprendedora”, hacen referencia al software web prestado como servicio por parte de la empresa Cultura Emprendedora, incluidos todos sus contenidos.</p>
                                        <p>o El término "titular de la cuenta" hace referencia a la persona a nombre de quien está la tarjeta de crédito / débito o el depósito bancario que se usó para registrar la cuenta en Cultura Emprendedora.</p>
                                        <p>o El término “cuenta” hace referencia a la instancia o espacio creado por el titular de la cuenta para operar el software Cultura Emprendedora de acuerdo a su Plan adquirido.</p>
                                        <p>o El término "usuario" hace referencia a la persona que visita y usa el sitio web de Cultura Emprendedora y su aplicación, sea o no "titular de cuenta"</p>
                                        <p>o El término "usuario administrador" hace referencia al usuario que tiene la facultad de habilitar y crear nuevos usuarios en la plataforma Cultura Emprendedora, delimitándoles sus perfiles de acceso; el titular de la cuenta es un usuario administrador por defecto quien a su vez puede crear nuevos usuarios administradores.</p>
                                        <p>o El término "Plan" hace referencia a las condiciones de uso que tiene un usuario según el pago que haya efectuado.</p>
                                    <h3>Registro de Cuentas y Usuarios</h3>
                                        <p>Cultura Emprendedora Soluciones presta un servicio de software que se accede a través de su sitio web www.culturaemprendedora.online y/o del dominio culturaemprendedora.online Los titulares de las cuentas que accedan a este servicio deberán registrar una cuenta y brindar la información solicitada en los formularios que se habilitan a la hora de registrarla. Cultura Emprendedora da por entendido que cualquier información ingresada en estos formularios es hecha bajo juramento y por lo tanto exonera a Cultura Emprendedora de poseer información falsa sobre cualquier titular.</p>
                                        <p>Para ser un usuario de la plataforma Cultura Emprendedora es necesario que el titular de la cuenta o usuario administrador delegado le asigne y le registre sus credenciales de acceso: usuario y contraseña, para su posterior uso; para ello, cada institución definirá las condiciones específicas que deba cumplir cada usuario a fin de otorgarle los medios de acceso y uso al sistema de información, quedando bajo su autonomía la creación, modificación o eliminación de sus usuarios.</p>
                                        <p>Cultura Emprendedora permite el ingreso de una cantidad limitada de usuarios según el plan que cada titular o usuario de cuenta haya elegido al momento de registrar su cuenta. Cultura Emprendedora no permite, bajo ninguna circunstancia, que estos usuarios sean distintos de aquellos que el titular de la cuenta haya decidido habilitar como tales para el uso de la plataforma y estos no podrán ser reemplazados por otras personas que conozcan las credenciales para ingresar a la plataforma. De suceder una situación como ésta, Cultura Emprendedora no se hace responsable por el uso pernicioso de la información de la cuenta en contra del titular de la misma ni frente al usuario ni frente a terceros.</p>
                                    <h3>Derechos de Autor</h3>
                                        <p>Los derechos de autor sobre la plataforma Cultura Emprendedora y demás servicios agregados, son de titularidad de la empresa Cultura Emprendedora y bajo ninguna interpretación de estos términos y condiciones se entenderán transferidos al usuario.</p>
                                        <p>La empresa Cultura Emprendedora en la actualidad presta el servicio de la plataforma Cultura Emprendedora, en cada uno de sus planes, bajo dos modalidades: la primera, gratuita con una expiración de 7 días calendario contados a partir de la creación de la cuenta y la segunda, de pago con las condiciones seleccionadas al momento de contratar la cuenta por parte del titular o usuario, quien adquiere una licencia de uso no exclusiva, mundial y temporal e intransferible para usar el sistema de información.</p>
                                        <p>El servicio de Cultura Emprendedora se inicia desde el momento de registrar una cuenta en su sitio web, una vez el titular de la misma y/o los usuarios hayan aceptado las condiciones expresadas en este contrato. El servicio consiste en el uso del software Cultura Emprendedora y demás servicios agregados, disponibles en el dominio culturaemprendedora.online, orientados a la gestión de la información académica y administrativa en las instituciones de educación, pudiendo incluir de acuerdo al plan elegido las siguientes funcionalidades: Gestión de clientes potenciales, inscripciones y matrículas, gestión de documentos digitales, gestión de grupos, cursos, horarios, aulas y docentes, gestión de homologaciones, habilitaciones y planes de mejoramiento, evaluación por competencias o evaluación cuantitativa, educación virtual integrada, administración de contenido dinámico, publicación de anuncios, cuestionarios, foros, tareas, gestión de tesorería (recibos, facturación, boletas), ingresos y egresos, gestión de cartera, órdenes de pago, créditos educativos, pagarés, proyección de recaudos, cuadres de caja, paz y salvos (constancias de no adeudo), gestión de egresados, ofertas laborales, informes académicos estadísticos, constancias, certificados y formatos de calidad, gestión de solicitudes, creación, recopilación y administración de encuestas institucionales.</p>
                                        <p>El usuario manifiesta tener pleno conocimiento de los servicios por los que está o no está pagando a la hora de usar alguno de los planes que ofrece Cultura Emprendedora, quien no se hará responsable en ningún caso por los errores cometidos por el usuario a la hora de elegir su plan.</p>
                                        <p>Cultura Emprendedora da por entendido que el titular de la cuenta y los usuarios conocen cualquier cambio que se haga en la configuración de ésta. Cultura Emprendedora no se responsabilizará por la pérdida de información que ocurra por fuerza mayor, caso fortuito o hecho de un tercero tal y como se explica bajo el título “Operación del Sitio”.</p>
                                        <p>Cultura Emprendedora garantiza al usuario el libre acceso a la plataforma para gestionar la información allí disponible, bajo condiciones normales; sin embargo, el usuario acepta que existan circunstancias técnicas por las que ésta información puede llegar a estar inaccesible de manera temporal y por lo tanto exonera a Cultura Emprendedora de cualquier tipo de responsabilidad por este hecho, bajo el entendido de que esto puede obedecer a mantenimientos o actualizaciones del sistema, o a limitaciones inherentes al estado de la tecnología en la actualidad.</p>
                                    <h3>Alcance y Nivel de Servicio</h3>
                                        <p>En condiciones normales, la plataforma Cultura Emprendedora y sus servicios agregados tienen un “down time” de aproximadamente el 1%, de tal manera que se encuentran disponibles el 99% del tiempo.</p>
                                        <p>Cultura Emprendedora realizará todas las actividades que considere pertinentes para que la plataforma se encuentre disponible para su uso, mas no lo garantiza, toda vez que pueden existir eventos como: daños en las comunicaciones, actos de terceros, mantenimiento o reestructuración de la aplicación, entre otros, que escapen al control y responsabilidad deCultura Emprendedora. No obstante lo anterior, Cultura Emprendedora garantiza que la aplicación estará disponible en circunstancias normales vía Internet, según lo anunciado, no requiriendo de instalaciones en equipos situados en el domicilio del usuario, siempre y cuando el mismo se encuentre activo para el uso de la aplicación, haga uso de las credenciales correctas de su cuenta y las condiciones de prestación del servicio de conexión a Internet por parte de cada proveedor lo permitan, no siendo responsabilidad de Cultura Emprendedora el no funcionamiento o el funcionamiento deficiente causado por el servicio de banda ancha contratado por el usuario.</p>
                                        <p>Cultura Emprendedora se encuentra facultado, sin necesidad de autorización por parte del usuario, para realizar las modificaciones o ajustes sobre la estructura técnica de la base de datos y de las aplicaciones que hacen parte del sistema Cultura Emprendedora, toda vez que ésta es de propiedad de la empresa Cultura Emprendedora, aunque éste último reconoce que la información es de propiedad del usuario. Igualmente, Cultura Emprendedora procurará informar oportunamente aquellos cambios que estime convenientes para evitar incomodidades o eventuales perjuicios en el procesamiento de la información.</p>
                                        <p>Cultura Emprendedora brindará un servicio postventa 100% virtual al usuario administrador, de acuerdo al plan elegido, a través de diferentes canales de atención y herramientas tecnológicas como: manual en línea, chat, asistencia remota, atención telefónica o email, los días no feriados, de lunes a viernes de 8:00 a.m. a 5:00 p.m en jornada continua y los sábados de 8:00 a.m. a 12 m., de acuerdo a la zona horaria de referencia UTC-05.</p>
                                    <h3>Medios de Pago</h3>
                                        <p>El titular de la cuenta o usuario podrá elegir el plan y periodo de pago al momento de realizar el primer pago. Según el periodo elegido: semestral o anual, el próximo cobro se realizará transcurrido el tiempo de dicho periodo contratado contado a partir del primer pago efectuado.</p>
                                        <p>El pago es anticipado y el usuario acepta que se realicen cobros recurrentes según los periodos elegidos. Además se compromete a notificar a Cultura Emprendedora en caso tal de que no quiera que se genere el siguiente cobro, mínimo 2 días hábiles antes de su próxima fecha de cobro.</p>
                                        <p>En caso de que el usuario no notifique a Cultura Emprendedora, con anticipación sobre su deseo de no generar el cobro recurrente, este tendrá 5 días hábiles para pedir la devolución del dinero conforme el derecho de retracto previsto en el Estatuto del Consumidor.</p>
                                        <p>Cultura Emprendedora ofrece los medios de pago que se reseñan en su página web. Sin embargo, para acceder a sus servicios a través de algunos de estos sistemas de pago, puede ser necesario registrar por parte del titular de la cuenta alguna información, como por ejemplo un número de cuenta o tarjeta de crédito expedida por parte de una entidad financiera que se encuentre vigente, para poder realizar el cobro por los servicios prestados en la plataforma online disponible en el dominio www.culturaemprendedora.online o en la aplicación móvil. Si existen retenciones de cualquier tipo estas tendrán que ser asumidas por el usuario.</p>
                                        <p>Cultura Emprendedora es consciente que poseer información de tarjetas de crédito o cuentas bancarias de los usuarios es delicado. Por lo tanto, está comprometido con mantener esta información segura y aislada de usos inadecuados.</p>
                                        <p>Cultura Emprendedora da por hecho que la información de la tarjeta de crédito ingresada para crear una cuenta es conocida por el titular de la cuenta por lo tanto no se hace responsable por el uso inadecuado de tarjetas de crédito al momento de esta ser usada para registrar una cuenta, entendiéndose como uso irresponsable, la falsificación y suplantación de la identidad del titular la cuenta.</p>
                                        <p>Cultura Emprendedora, por lo tanto, se abstiene de llevar a cabo todo tipo de actos tendientes a la verificación de los datos personales del usuario para confrontarlos con los registrados en su tarjeta de crédito pues asume que quien brinde los mismos es su propio titular y por ello conoce datos a los que no tiene acceso cualquier persona, además de no tener bases de datos con las cuales confrontar tal información.</p>
                                        <p>Cultura Emprendedora, por lo tanto, se abstiene de llevar a cabo todo tipo de actos tendientes a la verificación de los datos personales del usuario para confrontarlos con los registrados en su tarjeta de crédito pues asume que quien brinde los mismos es su propio titular y por ello conoce datos a los que no tiene acceso cualquier persona, además de no tener bases de datos con las cuales confrontar tal información.</p>
                                        <p>El usuario afirma bajo la gravedad de juramento, que no está incluido en la Lista Clinton y que sus ingresos no tienen relación con ningún tipo de actos de aquellos que la legislación española e internacional determinan para el lavado de activos, narcotráfico, terrorismo ni otro delito y que son adquiridos de manera lícita.</p>
                                    <h3>Información de la cuenta</h3>
                                        <p>La plataforma Cultura Emprendedora es un aplicativo Web, el cual proporciona un sitio donde se alojan datos que el usuario administra bajo su cuenta y riesgo. Cultura Emprendedora vela por mantener la información de los usuarios, segura y toma las precauciones a su juicio necesarias para ello, mas no se responsabiliza por actos mal intencionado de terceros y las consecuencias de ello frente al usuario o frente a terceros.</p>
                                        <p>El usuario será el único responsable de la cantidad y la calidad de la información tanto personal como de la gestión institucional ingresada, modificada y/o eliminada en el sistema de información para su adecuado funcionamiento y resultados arrojados, estando obligado a hacer uso sano y legal de la plataforma en los términos en que ha sido contratado el servicio y en virtud de ello, deberá tomar las medidas preventivas usuales en la actividad de la computación, con el fin de evitar que eventualmente se produzcan fallas que le causen cualquier tipo de daño o perjuicio, bien sea a la institución que representa o a terceros. El titular de la cuenta, quien adquiere las credenciales iniciales con todos los privilegios de acceso al sistema Cultura Emprendedora, o su usuario administrador delegado deberá ejercer un adecuado control sobre los usuarios a los cuales les autorice acceso delimitándoles claramente sus autorizaciones y responsabilidades. En todo caso, Cultura Emprendedora queda exonerado de cualquier uso indebido de la información por parte de cualquier usuario.</p>
                                        <p>El usuario de la plataforma Cultura Emprendedora manifiesta ser dueño de la información que ingresa en el sistema y bajo ninguna circunstancia esta información pasará a ser propiedad de Cultura Emprendedora, y de manera inversa, esta última sociedad es la única dueña de la plataforma sobre la cual el usuario ingresa la información, sin que respecto de ésta se considera surtida transferencia alguna en razón de éste contrato. Si el usuario da por terminado el contrato, a partir de su finalización, contará con un plazo de 45 días calendario para descargar una copia de seguridad con la última versión de la información estructurada almacenada en la plataforma, en el formato XML, pero en ningún momento Cultura Emprendedora se obliga a entregar la misma en otro formato diferente ni a llevar a cabo ningún tipo de proceso de migración, ni mucho menos a efectuar un desarrollo para que la información pueda ser analizada, ingresada o digitalizada en cualquier otro software.</p>
                                        <p>Adicional a lo anterior, Cultura Emprendedora no se responsabiliza por el mal diligenciamiento de un formulario o por la información que erróneamente suministre el usuario al momento de realizar un trámite o de ingresar la información al software.</p>
                                        <h3>Seguridad de la Cuenta</h3>
                                        <p>Cultura Emprendedora vela por la seguridad de la contraseña que provea el titular de cuenta y los usuarios a la hora de registrar una cuenta en la plataforma y garantiza que tomará las medidas que se encuentren a su alcance para que esta contraseña no sea vista por terceros, mas no puede arrogarse la responsabilidad de garantizar su confidencialidad. Por otro lado, Cultura Emprendedora no se responsabiliza por el mal uso de la contraseña por parte del usuario ni por el uso de contraseñas que sean fáciles de descifrar, asumiendo que siempre que se acceda al sistema, lo hace el usuario directamente.</p>
                                    <h3>Terminación e Interrupción del Servicio</h3>
                                        <p>Cultura Emprendedora se reserva el derecho de terminar el servicio en cualquier momento, tanto de manera permanente como temporal, para aquellos casos en los que se deban realizar pagos sucesivos.</p>
                                        <p>Cultura Emprendedora podrá terminar de manera unilateral la cuenta de un usuario en los siguientes escenarios: (i) En caso de que el usuario utilice los servicios prestados por Cultura Emprendedora para fines contrarios a la ley, especialmente aquellos que contraríen derechos de propiedad intelectual de terceros, de Cultura Emprendedora o de otros usuarios; (ii) En caso de que Cultura Emprendedora encuentre que el usuario está haciendo uso de su cuenta para la transmisión de programas malignos como virus, malwares, spywares, troyanos o similares, que puedan comprometer el debido funcionamiento de la plataforma de Cultura Emprendedora o que perjudiquen a terceros; (iii) Cuando existan elementos que permitan inferir a Cultura Emprendedora que el usuario no cuenta con la edad mínima para contratar los Servicios, en los términos de las condiciones preliminares de este contrato.</p>
                                        <p>Cultura Emprendedora se reserva el derecho a decidir si el contenido publicado por los usuarios, al igual que el material de texto o fotográfico que sea cargado a la página web de Cultura Emprendedora resulta apropiado y se ajusta a las condiciones. En éste sentido, Cultura Emprendedora podrá impedir la publicación y comercialización de contenido que infrinja derechos de imagen, de habeas data y de privacidad de terceros, así como aquellos que resulten ofensivos, difamatorios o que constituyan infracciones a la ley.</p>
                                    <h3>Suspensión del servicio</h3>
                                        <p>Cultura Emprendedora se reserva el derecho de suspender la prestación de los servicios al usuario y de inhabilitar su acceso al Software, así como a cualquiera de los módulos creados para el usuario si luego de dos intentos de cobro del servicio el recaudo resulta fallido, o en caso de no recibir el pago del servicio en la forma acordada. Se dará la suspensión del servicio al usuario con aviso anticipado.</p>
                                        <p>En caso de suspensión, la cuenta del usuario no será reactivada hasta que el pago de todas aquellas deudas que en ese momento se encuentren a cargo del usuario se hayan realizado por completo. Si luego de tres intentos de cobro del servicio el recaudo resulta fallido, el usuario debe realizar el pago del dinero adeudado mediante un enlace de pago el cual deberá solicitar a través de comunicación al correo: admin@culturaemprendedora.online</p>
                                        <p>La suspensión de la cuenta del usuario no elimina su obligación de pagar las deudas pendientes, así como tampoco el porcentaje cobrado impide la generación de los gastos de cobranza e indemnización de perjuicios que se pudiesen generar a favor de Cultura Emprendedora por tal incumplimiento.</p>
                                        <p>En caso de falta de pago, o uso indebido de la cuenta, el usuario recibirá a su correo una notificación a partir de la cual tendrá un periodo de gracia de 45 días calendario durante el cual podrá descargar una copia de seguridad con la última versión de la información estructurada almacenada en la plataforma Cultura Emprendedora, en el formato XML. Una vez venza dicho periodo, Cultura Emprendedora dejará de ser responsable de la información albergada en la cuenta y esta podrá ser eliminada libremente.</p>
                                    <h3>Operación del Sitio</h3>
                                        <p>Cultura Emprendedora llevará a cabo las gestiones que a su juicio estime conducentes, tendientes a que la plataforma siempre esté disponible para el usuario, pero no garantiza lo anterior, tanto por los daños en las comunicaciones, por actos de terceros, mantenimiento o reestructuración u otro tipo de actos que se escapen del alcance y responsabilidad directa de Cultura Emprendedora. No obstante lo anterior, Cultura Emprendedora garantiza a los usuarios que pagan por el servicio, que el software estará disponible desde cualquier lugar del mundo que permita una conexión a internet, siempre y cuando el usuario recuerde las credenciales de su cuenta y las condiciones de prestación del servicio de conexión a Internet por parte de cada proveedor, lo permitan.</p>
                                    <h3>Enlaces de Terceras Partes</h3>
                                        <p>Ciertos contenidos, productos o servicios disponibles en el sistema Cultura Emprendedora podrían incluir material de terceras partes. Determinados enlaces en este servicio podrían direccionar al usuario a sitios web de terceras partes que no están afiliadas con Cultura Emprendedora quien no se responsabiliza de examinar o evaluar su contenido o exactitud y no garantiza, ni se obliga o responsabiliza por cualquier material, productos o servicios de terceros.</p>
                                        <p>Cultura Emprendedora no se hace responsable de cualquier daño o daños relacionados con la adquisición o utilización de bienes, servicios, recursos, contenidos, o cualquier otra transacción realizada en conexión con sitios web de terceros. El usuario es el directo responsable en revisar cuidadosamente las políticas y prácticas de terceros y asegurarse de entenderlas antes de participar en cualquier transacción. Quejas, reclamos, inquietudes o preguntas con respecto a productos de terceros deben ser dirigidas a la tercera parte.</p>
                                    <h3>Logos</h3>
                                        <p>El usuario autoriza a Cultura Emprendedora el uso de los logos de las instituciones de educación participantes, en la página web: www.culturaemprendedora.online y portafolio de servicios, sección clientes, con la única intención de presentar la relación comercial vinculante entre las partes.</p>
                                        <h3>Política de privacidad</h3>
                                        <p>Funciones publicitarias de Google Analytics implementadas en Cultura Emprendedora utiliza las audiencias de remarketing de Google Analytics para su uso en Google AdWords y DoubleClick Bid Manager, esto con el fin de publicar campañas de remarketing dirigidas a sus usuarios. El usuario acepta que su información sea tratada para efectos de Big Data y por lo tanto permite que Cultura Emprendedora utilice estas herramientas con fines estadísticos.</p>
                                    <h3>Modo de uso de las cookies</h3>
                                        <p>Cultura Emprendedora, Mediante la instalación de cookies e identificadores propios y de terceros y a través de herramientas para el análisis de uso de cuenta, podrá realizar actividades de seguimiento a los usuarios que utilizan su aplicación. Con estas herramientas, Cultura Emprendedora podrá recopilar información de cada usuario para el análisis de estadísticas e implementación de estrategias de comunicación y publicidad. Estas herramientas podrán realizar seguimiento de la configuración del usuario y hacen que su experiencia en la aplicación sea más práctica, reconociendo y recordando sus preferencias y ajustes.</p>  
                                        <p>En esta medida, Cultura Emprendedora podrá recopilar datos de uso, como la duración de uso, o datos demográficos como el origen, el sexo y la edad. Cultura Emprendedora usa esta información para fines analíticos. El usuario de Cultura Emprendedora podrá deshabilitar estas herramientas.</p>  
                                        <p>Las actividades de seguimiento adelantadas por Cultura Emprendedora también podrán realizarse dentro de la aplicación, para análisis interno, ejemplo, pero no exclusivamente para determinar tendencias y participación en la aplicación, tiempo de uso, preferencia, entre otros. Estas herramientas podrán ser desactivadas por el usuario ‘para conservar su privacidad. Ver más aquí.</p>  
                                        <h3>Análisis de datos</h3>
                                        <p>El usuario al crear su cuenta y/o al hacer uso de la aplicación, acepta que Cultura Emprendedora puede suministrar, transferir, compartir y analizar los datos del giro ordinario de su negocio, con empresas aliadas, filiales, vinculadas o subordinadas de Cultura Emprendedora en España o cualquier otro país, esta información podrá ser usada para fines comerciales por parte de los terceros.</p>  
                                        <p>otro país, esta información podrá ser usada para fines comerciales por parte de los terceros. El usuario en cualquier momento puede solicitar a Cultura Emprendedora que detenga de forma indefinida el proceso de compartir sus datos con terceros, para esto debe realizar su solicitud al correo admin@culturaemprendedora.online o comunicarse a través del chat de atención al cliente.</p>  
                                    <h3>Política Comunicacional</h3>
                                        <p>Al registrar una cuenta con Cultura Emprendedora el titular de la cuenta debe introducir un email y un teléfono de contacto, así como registrar todos aquellos datos que el software le solicite a fin de determinar no solo su identificación, sino aquello que le permita al software procesar la información que el mismo usuario diligencie o ingrese. Al hacer esto, acepta recibir todos los correos y llamadas con información sobre el uso de la plataforma Cultura Emprendedora, información promocional u otro tipo de información procesada o enviada por Cultura Emprendedora. No obstante lo anterior, Cultura Emprendedora no podrá utilizar en beneficio suyo o de terceros, la información que haya ingresado el usuario, sin embargo, podrá utilizar la base de datos de las empresas o usuarias con fines publicitarios o comerciales para sí o para terceros, sin que por ello deba participar de ingreso alguno a los usuarios. El usuario podrá solicitar que sus datos dejen de ser compartidos en cualquier momento y por medio de los canales establecidos y/o a la siguiente dirección de correo electrónico: admin@culturaemprendedora.online</p>  
                                        <p>Esta cláusula se interpretará sin detrimento de la autorización de uso de información a que se refiere el título “Política de Privacidad”. La autorización a que se refiere ésta cláusula podrá ser revocada por el usuario en cualquier tiempo escribiendo a la siguiente dirección de correo electrónico: admin@culturaemprendedora.online</p>  
                                        <p>Adicionalmente los usuarios tendrán habilitada la posibilidad de comunicarse con el equipo de Cultura Emprendedora en caso de que tengan preguntas o dudas por resolver, preguntas generales sobre su cuenta o sobre el software como tal. Para los casos anteriores, deberán escribir a admin@culturaemprendedora.online o utilizar la pestaña de soporte disponible en la aplicación.</p>  
                                    <h3>Comentarios y Preguntas</h3>
                                        <p>En caso de existir consultas, quejas o reclamos sobre la información contenida en el presente documento de Términos y Condiciones, por favor escribir al correo admin@culturaemprendedora.online, utilizando como asunto: Comentario Términos y Condiciones.</p>  
                                </div>
                            </div>

                        <div class="row align-items-center justify-content-center">
                            <div class="block-break"></div>
                            <div id="block-1598224544471" class="block-type--cta text-center col-6" data-reveal-units="seconds">
                                <div class="block box-shadow-none background-unrecognized aos-init aos-animate" data-aos="none" data-aos-delay="0" data-aos-duration="0">
                                    <a class="btn btn-large btn-solid btn-full background-light" href="<?php echo site_url();?>">
                                        VOLVER AL INICIO 
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <div id="section-footer">
        <?php $this->load->view("footer"); ?>
    </div>
    <script
        src="<?php echo site_url() . "static/page_front/js/encore_core-391b174ddfaf72e8ec9615d1579235b5c2c755e7cd65e22cf10938c815f7f394.js"; ?>">
    </script>
    <script src="<?php echo site_url() . "static/page_front/js/scripts.js?15964308185009978"; ?>"></script>
    <script src="<?php echo site_url() . 'script.js'; ?>"></script>
</body>

</html>